[versions]
groovy = "4.0.23"
jetty = "9.4.44.v20210927"
junit4 = "4.13.2"
junit5 = "5.8.1"
ratpack = "1.10.0-milestone-32"
sauceConnect = "1.153"
selenium = "4.2.2"
spock = "2.4-M4-groovy-4.0"
threeTen = "1.7.0"

[libraries]
asciidoctorj = 'org.asciidoctor:asciidoctorj:2.5.2'
cglib = 'cglib:cglib:2.2'
codenarcGroovy4 = 'org.codenarc:CodeNarc:3.1.0-groovy-4.0'
codenarc = 'org.codenarc:CodeNarc:2.2.0'
commons-fileupload = 'commons-fileupload:commons-fileupload:1.3.1'
gebSpockGroovy25 = 'org.gebish:geb-spock:4.0'
grolifant = 'org.ysb33r.gradle:grolifant80:4.0.0'
groovy-bom = { module = 'org.apache.groovy:groovy-bom', version.ref = 'groovy' }
groovy25 = 'org.codehaus.groovy:groovy-all:2.5.14'
guava = 'com.google.guava:guava:23.0'
htmlUnitDriver = 'org.seleniumhq.selenium:htmlunit-driver:3.62.0'
jetty-server = { module = 'org.eclipse.jetty:jetty-server', version.ref = 'jetty' }
jetty-servlet = { module = 'org.eclipse.jetty:jetty-servlet', version.ref = 'jetty' }
jodd-core = 'org.jodd:jodd-core:5.3.0'
jodd-lagarto = 'org.jodd:jodd-lagarto:6.0.5'
jsoup = 'org.jsoup:jsoup:1.14.3'
junit-platform-launcher = 'org.junit.platform:junit-platform-launcher:1.8.1'
junit-platform-testkit = 'org.junit.platform:junit-platform-testkit:1.8.1'
junit4 = { module = 'junit:junit', version.ref = 'junit4' }
junit5-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit5' }
junit5-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit5' }
junit5-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params', version.ref = 'junit5' }
junit5-vintage-engine = { module = 'org.junit.vintage:junit-vintage-engine', version.ref = 'junit5' }
ratpack-test = {module = 'io.ratpack:ratpack-test', version.ref = 'ratpack' }
sauceConnect = { module = 'com.saucelabs:ci-sauce', version.ref = 'sauceConnect' }
selenium-api = { module = 'org.seleniumhq.selenium:selenium-api', version.ref = 'selenium' }
selenium-grid = { module = 'org.seleniumhq.selenium:selenium-grid', version.ref = 'selenium' }
selenium-support = { module = 'org.seleniumhq.selenium:selenium-support', version.ref = 'selenium' }
spock-core = { module = 'org.spockframework:spock-core', version.ref = 'spock' }
spockCoreGroovy25 = 'org.spockframework:spock-core:1.3-groovy-2.5'
spockCoreGroovy3 = 'org.spockframework:spock-core:2.3-groovy-3.0'
systemLambda = 'com.github.stefanbirkner:system-lambda:1.2.0'
testcontainers-selenium = 'org.testcontainers:selenium:1.17.2'
testng = 'org.testng:testng:6.14.3'
threeTen-extra = { module = 'org.threeten:threeten-extra', version.ref = 'threeTen' }

[plugins]
asciidoc = { id = 'org.asciidoctor.jvm.convert', version = '3.3.2' }
asl2 = { id = 'com.energizedwork.asl2', version = '1.1' }
nexusPublish = { id = 'io.github.gradle-nexus.publish-plugin', version = '1.0.0' }
node = { id = 'com.github.node-gradle.node', version = '3.5.0' }
ratpackGroovy = { id = 'io.ratpack.ratpack-groovy', version.ref = 'ratpack' }
webdriverBinaries = { id = 'com.github.erdi.webdriver-binaries', version = '3.2.0-gradle8' }
